name: release

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '0 3 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push net6.0
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: net6.0.Dockerfile
          tags: lyra1337/aspnet-chromium:net6.0

      - name: Build and push net7.0
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: net7.0.Dockerfile
          tags: lyra1337/aspnet-chromium:net7.0

      - name: Build and push net8.0
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: net8.0.Dockerfile
          tags: lyra1337/aspnet-chromium:latest,lyra1337/aspnet-chromium:net8.0

      - name: Build and push net9.0
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: net9.0.Dockerfile
          tags: lyra1337/aspnet-chromium:latest,lyra1337/aspnet-chromium:net9.0

